Api update dukument navn
navikt/syk-dig-backend pull request #68
Opened 2023-04-20 14:45 UTC by andreasDev

2023-04-21 05:14 UTC, MikAoJk commented
Må oppdarere OppgaveMapper.kt med 
fra
`digitaliseringsoppgave.dokumenter?.map`
til
`digitaliseringsoppgave.dokumenter.map`

2023-04-21 05:16 UTC, MikAoJk requested changes
Må oppdarere OppgaveMapper.kt med 
fra
`digitaliseringsoppgave.dokumenter?.map`
til
`digitaliseringsoppgave.dokumenter.map`

2023-04-26 12:49 UTC, MikAoJk requested changes

2023-04-26 12:49 UTC, MikAoJk commented on naiserator-dev.yaml
> +          cluster: prod-fss
Skulle det stått dev-fss her?

2023-04-28 06:15 UTC, andreasDev commented on naiserator-dev.yaml
> +          cluster: prod-fss
nei skal være prod

2023-04-28 06:15 UTC, merged